services:
  - type: web
    name: bankmate-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_ORIGIN
        value: ${CLIENT_ORIGIN}
      - key: PORT
        value: 10000